public enum ConstructionSector
{
    Alpha   = 0,
    Bravo   = 1,
    Charlie = 2,
    Delta   = 3,
    Echo    = 4,
    Foxtrot = 5,
    Golf    = 6,
    Hotel   = 7,
    India   = 8,
    Juliet  = 9,
    Kilo    = 10,
    Lima    = 11,
    Mike    = 12,
    November= 13,
    Oscar   = 14,
    Papa    = 15,
    Quebec  = 16,
    Romeo   = 17,
    Tango   = 18,
    BaseTeam = 100,
}
